'use client';

import { useState } from 'react';

type Settings = any; // Just for simplicity, we pass the full object

export default function SitemapClientForm({ 
  settings, 
  liveUrls, 
  defaultRobotsTxt 
}: { 
  settings: Settings; 
  liveUrls: { type: string, slug: string }[];
  defaultRobotsTxt: string;
}) {
  const [sitemapText, setSitemapText] = useState(settings?.customSitemapUrls || '');
  const [override, setOverride] = useState(settings?.overrideSitemap || false);

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://madmarketer.com';

  const handleLoadAutoGenerated = () => {
    const urlsToLoad = liveUrls.map(u => `${baseUrl}${u.slug}`).join('\n');
    setSitemapText(urlsToLoad);
    setOverride(true); // Automatically check override when loading full sitemap
  };

  const inputStyle = { width: '100%', padding: '0.75rem', marginBottom: '1.5rem', background: '#222', border: '1px solid #444', color: '#fff', borderRadius: '4px' };

  return (
    <>
      <div style={{ marginBottom: '1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <h3 style={{ margin: 0 }}>Custom Sitemap Entries</h3>
        <button type="button" onClick={handleLoadAutoGenerated} style={{ background: '#333', color: '#fff', border: '1px solid #555', padding: '0.5rem 1rem', borderRadius: '4px', cursor: 'pointer', fontSize: '0.85rem' }}>
          Load Auto-Generated URLs
        </button>
      </div>

      <p style={{ color: '#888', fontSize: '0.9rem', marginBottom: '1rem' }}>
        Enter any external or manual URLs here to append them to the sitemap (one per line).
      </p>

      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
        <input 
          type="checkbox" 
          id="overrideSitemap" 
          name="overrideSitemap" 
          value="true"
          checked={override}
          onChange={(e) => setOverride(e.target.checked)}
        />
        <label htmlFor="overrideSitemap" style={{ color: '#ED1C24', fontWeight: 'bold', fontSize: '0.95rem' }}>
          Override Auto-Generated Sitemap (Only output URLs in box below)
        </label>
      </div>

      <textarea 
        name="customSitemapUrls" 
        value={sitemapText}
        onChange={(e) => setSitemapText(e.target.value)}
        placeholder="https://example.com/custom-page" 
        style={{ ...inputStyle, height: '250px', fontFamily: 'monospace' }} 
      />

      <h3 style={{ marginTop: '2rem', marginBottom: '1rem', paddingBottom: '0.5rem', borderBottom: '1px solid #333' }}>Robots.txt Editor</h3>
      <p style={{ color: '#888', fontSize: '0.9rem', marginBottom: '1rem' }}>
        Override the default crawler rules. Leave blank to use the safe defaults.
      </p>
      <textarea 
        name="customRobotsTxt" 
        defaultValue={settings?.customRobotsTxt || defaultRobotsTxt} 
        style={{ ...inputStyle, height: '150px', fontFamily: 'monospace' }} 
      />

      <button type="submit" style={{ background: '#ED1C24', color: '#fff', border: 'none', padding: '1rem 2rem', borderRadius: '4px', cursor: 'pointer', fontSize: '1.1rem', fontWeight: 'bold' }}>
        Save Sitemap & Robots
      </button>
    </>
  );
}
